- name: try running copying key
  ansible.builtin.command: "ssh-copy-id {{ hostvars[item]['ansible_user'] }}@{{ item }}"
  ignore_errors: true
  changed_when: ssh_copy.stdout != ""
  register: ssh_copy
  with_items: "{{ hostvars.keys() }}"

- name: set fact
  vars:
    ssh_stdout: "{{ ssh_copy['results'] | map(attribute='stdout') }}"
    ssh_host: "{{ ssh_copy['results'] | map(attribute='item') }}"
  set_fact:
    ssh_changed: |-
      {% for item in range( (ssh_host | length) -1 ,-1,-1) %}
      {% if ssh_stdout[item] != "" %}
      {{ ssh_host[item] }}
      {% endif %}
      {% endfor %}

- name: disp fact
  debug:
    msg: "{{ item }} has had the new authorization key added to ssh"
  with_items: "{{ ssh_changed.split('\n') | select('!=','') }}"
  when: ssh_changed.split('\n')[0] != ""
